### PR TITLE
Update link to spreadsheet toolbox

### PR DESCRIPTION
**Pull request by mtausig**
The link on the website pointing to the spreadsheet toolbox is currently still pointing to the old version (containing bugs) from the old archived github repository.
This PR updates it to the current version 2.0.2.

### CODE REVIEW

**Comment by RossBarnie** [comment]
This would need updated with every release. I think a more sustainable change would be to point to the releases page, rather than the specific version.

**Comment by mtausig** [comment]
Better like this?
I would still prefer the original version to the patch, as it links directly to the spreadsheet.

**Comment by RossBarnie** [comment]
Even better!

**Comment by mtausig** [comment]
Fixed conflict with main

**Review by SebaDele — APPROVED** [review]

**Pull request merged**
